#!/usr/bin/env perl

use strict;
use warnings;

my $logfile = shift @ARGV or die "Usage: demux.pl md.log [extra]\n";
my $extra   = shift @ARGV // 0;

open my $fh, "<", $logfile or die "Cannot open $logfile: $!\n";

my $nrep = 0;
my @order = ();
my @times = ();
my @history = ();
my $current_time = 0.0;

sub write_outputs {
    my ($times_ref, $history_ref, $nreplicas) = @_;

    open my $idx, ">", "replica_index.xvg" or die "Cannot write replica_index.xvg: $!\n";
    open my $tmp, ">", "replica_temp.xvg"  or die "Cannot write replica_temp.xvg: $!\n";

    print {$idx} "# replica_index.xvg generated by demux.pl\n";
    print {$tmp} "# replica_temp.xvg generated by demux.pl\n";

    for my $frame (0 .. $#{$history_ref}) {
        my $time = $times_ref->[$frame];
        my @state = @{ $history_ref->[$frame] };
        print {$idx} join(" ", sprintf("%.3f", $time), @state), "\n";

        my @inverse = (0) x $nreplicas;
        for my $ladder (0 .. $#state) {
            $inverse[$state[$ladder]] = $ladder;
        }
        print {$tmp} join(" ", sprintf("%.3f", $time), @inverse), "\n";
    }

    close $idx;
    close $tmp;
}

while (my $line = <$fh>) {
    chomp $line;

    if ($line =~ /Replica exchange at step .* time\s+([0-9Ee+\-\.]+)/) {
        $current_time = $1 + 0.0;
        next;
    }

    next unless $line =~ /^Repl ex/;

    my @tokens = split /\s+/, $line;
    shift @tokens;    # Repl
    shift @tokens;    # ex

    if (!$nrep) {
        my $max_index = 0;
        for my $tok (@tokens) {
            next if $tok eq 'x';
            $max_index = $tok if $tok =~ /^\d+$/ && $tok > $max_index;
        }
        $nrep = $max_index + 1;
        @order = (0 .. $nrep - 1);
    }

    my @exchanges = grep { $_ ne '' } @tokens;
    for (my $i = 0; $i < $#exchanges; $i++) {
        next unless $exchanges[$i] eq 'x';
        my $left  = $exchanges[$i - 1];
        my $right = $exchanges[$i + 1];
        next unless defined $left && defined $right;
        next unless $left =~ /^\d+$/ && $right =~ /^\d+$/;
        ($order[$left], $order[$right]) = ($order[$right], $order[$left]);
    }

    my @snapshot = @order;
    if ($extra) {
        push @snapshot, (0) x $extra;
    }
    push @times, $current_time;
    push @history, [@snapshot];
}

close $fh;

die "No replica exchange lines found in $logfile\n" unless @history;

write_outputs(\@times, \@history, scalar @{ $history[0] });
